### PR TITLE
Adds support for route-level redirects

### PR DESCRIPTION
**Pull request by harman28**
Let's you do [this](https://github.com/harman28/lightsaber/blob/master/redirects.yml#L17):

```sh
# where.rzp.io/delhi -> https://goo.gl/maps/1A9nhMPzehS2
# where.rzp.io/gurgaon -> https://goo.gl/maps/PX2apgMYQ6L2
where.rzp.io:
  delhi: https://goo.gl/maps/1A9nhMPzehS2
  gurgaon: https://goo.gl/maps/PX2apgMYQ6L2
```

Defaults to first option if no route is given.

### CODE REVIEW

**Comment by captn3m0** [comment]
I like this very much, except it breaks with the future planning I have in #3 #4 (because we don't have a YAML structure anymore inside the CNAME).

**Comment by harman28** [comment]
Closing this as it is at odds with #3. 

Note, for someone who sees this and is interested: this is merged with [harman28/lightsaber:master](https://github.com/harman28/lightsaber)

**Comment by captn3m0** [comment]
There is a way to support this just with DNS. See the last few comments at #3.

**Comment by stp-ip** [comment]
Btw. this is how we do it with redirects stored in DNS: https://github.com/txtdirect/txtdirect/blob/master/examples/README.md#path

**Pull request closed without merging**
